#!/usr/bin/env sh
set -eu

usage() {
  cat >&2 <<'EOF'
Usage: activate.sh --bundle DIRECTORY --compose-root DIRECTORY --env-file FILE

Activation is deliberately explicit. Set DATAOS_ACTIVATE_CONFIRM=YES during a
change window; the script keeps the previous configuration and image reference
under .data-os-seatunnel and never deletes volumes.
EOF
  exit 64
}

bundle_dir=
compose_root=
env_file=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --bundle)
      [ "$#" -ge 2 ] || usage
      bundle_dir=$2
      shift 2
      ;;
    --compose-root)
      [ "$#" -ge 2 ] || usage
      compose_root=$2
      shift 2
      ;;
    --env-file)
      [ "$#" -ge 2 ] || usage
      env_file=$2
      shift 2
      ;;
    -h|--help) usage ;;
    *) echo "unknown option: $1" >&2; usage ;;
  esac
done

[ -n "$bundle_dir" ] && [ -n "$compose_root" ] && [ -n "$env_file" ] || usage
[ "${DATAOS_ACTIVATE_CONFIRM:-}" = YES ] || {
  echo 'refusing activation: set DATAOS_ACTIVATE_CONFIRM=YES in the approved change window' >&2
  exit 77
}
[ -f "$compose_root/docker-compose.yml" ] || { echo 'compose root has no docker-compose.yml' >&2; exit 66; }
[ -f "$env_file" ] || { echo "env file does not exist: $env_file" >&2; exit 66; }
runtime_env=$(sed -n 's/^[[:space:]]*DATAOS_RUNTIME_ENV[[:space:]]*=[[:space:]]*//p' "$env_file" | tail -n 1 | tr '[:upper:]' '[:lower:]' || true)
if [ "${DATAOS_ALLOW_UNSIGNED:-false}" = true ] && [ "$runtime_env" != development ]; then
  echo 'unsigned activation is allowed only with DATAOS_RUNTIME_ENV=development' >&2
  exit 78
fi

if [ "${DATAOS_ALLOW_UNSIGNED:-false}" = true ]; then
  if [ -n "${DATAOS_RELEASE_PUBLIC_KEY:-}" ]; then
    "$bundle_dir/scripts/verify-offline-bundle.sh" --bundle "$bundle_dir" \
      --allow-unsigned --public-key "$DATAOS_RELEASE_PUBLIC_KEY"
  else
    "$bundle_dir/scripts/verify-offline-bundle.sh" --bundle "$bundle_dir" --allow-unsigned
  fi
elif [ -n "${DATAOS_RELEASE_PUBLIC_KEY:-}" ]; then
  "$bundle_dir/scripts/verify-offline-bundle.sh" --bundle "$bundle_dir" \
    --public-key "$DATAOS_RELEASE_PUBLIC_KEY"
else
  "$bundle_dir/scripts/verify-offline-bundle.sh" --bundle "$bundle_dir"
fi

command -v docker >/dev/null 2>&1 || { echo 'docker is required' >&2; exit 69; }
manifest_image_ref=$(sed -n 's/.*"imageRef"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$bundle_dir/release-manifest.json")
[ -n "$manifest_image_ref" ] || { echo 'imageRef is missing from release manifest' >&2; exit 65; }
# After offline import the hospital may retag the same image under its private
# OCI registry. The optional override is accepted only when the loaded image ID
# still matches the signed manifest below.
image_ref=${DATAOS_ACTIVATION_IMAGE:-$manifest_image_ref}
# A release manifest is generated by this repository, but reject malformed
# image refs before putting one into a dotenv file. Newlines/whitespace here
# would change the meaning of the operator configuration.
case "$image_ref" in
  ''|*[!A-Za-z0-9._/@:+-]*)
    echo "imageRef contains unsupported characters: $image_ref" >&2
    exit 65
    ;;
esac
docker image inspect "$image_ref" >/dev/null 2>&1 || {
  echo "import image before activation: $image_ref" >&2
  exit 69
}
manifest_image_id=$(sed -n 's/.*"imageId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$bundle_dir/release-manifest.json")
loaded_image_id=$(docker image inspect --format '{{.Id}}' "$image_ref")
[ -n "$manifest_image_id" ] && [ "$loaded_image_id" = "$manifest_image_id" ] || {
  echo "loaded image does not match release manifest: $image_ref" >&2
  exit 65
}
docker run --rm --entrypoint sh "$image_ref" -c '
  ! find /opt/seatunnel -type f \( -iname "*shell*" -o -iname "*connector-shell*" \) -print -quit | grep -q . &&
  ! grep -Eiq "(^|[^[:alnum:]])shell([^[:alnum:]]|$)" /opt/seatunnel/connectors/plugin-mapping.properties
' || {
  echo 'Shell plugin detected in loaded image' >&2
  exit 65
}

state_dir="$compose_root/.data-os-seatunnel"
timestamp=$(date -u +%Y%m%dT%H%M%SZ)
backup_dir="$state_dir/backups/$timestamp"
mkdir -p "$backup_dir"
chmod 700 "$state_dir" "$state_dir/backups" "$backup_dir"
previous_image=$(sed -n 's/^SEATUNNEL_IMAGE[[:space:]]*=[[:space:]]*//p' "$env_file" | tail -n 1 || true)
[ -n "$previous_image" ] || previous_image=none
printf '%s\n' "$previous_image" > "$backup_dir/previous-image"
cp "$env_file" "$backup_dir/env-file"
chmod 600 "$backup_dir/previous-image" "$backup_dir/env-file"
if [ -f "$compose_root/seatunnel/seatunnel.yaml" ]; then
  cp "$compose_root/seatunnel/seatunnel.yaml" "$backup_dir/seatunnel.yaml"
fi
if [ -f "$compose_root/seatunnel/seatunnel-compose.yml" ]; then
  cp "$compose_root/seatunnel/seatunnel-compose.yml" "$backup_dir/seatunnel-compose.yml"
fi
cp "$bundle_dir/release-manifest.json" "$backup_dir/release-manifest.json"

mkdir -p "$compose_root/seatunnel"
cp "$bundle_dir/deploy/seatunnel.yaml" "$compose_root/seatunnel/seatunnel.yaml"
cp "$bundle_dir/deploy/seatunnel-compose.yml" "$compose_root/seatunnel/seatunnel-compose.yml"

activation_state=prepared
restore_on_failure() {
  status=$?
  if [ "$status" -ne 0 ] && [ "$activation_state" = prepared ]; then
    cp "$backup_dir/env-file" "$env_file" 2>/dev/null || true
    if [ -f "$backup_dir/seatunnel.yaml" ]; then
      cp "$backup_dir/seatunnel.yaml" "$compose_root/seatunnel/seatunnel.yaml" 2>/dev/null || true
    fi
    if [ -f "$backup_dir/seatunnel-compose.yml" ]; then
      cp "$backup_dir/seatunnel-compose.yml" "$compose_root/seatunnel/seatunnel-compose.yml" 2>/dev/null || true
    fi
    if [ "$previous_image" != none ] && command -v docker >/dev/null 2>&1; then
      SEATUNNEL_IMAGE="$previous_image" docker compose --env-file "$env_file" \
        -f "$compose_root/docker-compose.yml" -f "$compose_root/seatunnel/seatunnel-compose.yml" \
        up -d seatunnel-master control-plane >/dev/null 2>&1 || true
    fi
  fi
  exit "$status"
}
trap restore_on_failure EXIT HUP INT TERM

# Make the new image the durable operator configuration. Compose receives the
# explicit variable below as well, so activation is deterministic even when
# the env file already contained a different tag or digest.
env_tmp=$(mktemp "$state_dir/.env.XXXXXX")
awk -v image="$image_ref" '
  BEGIN { replaced = 0 }
  /^[[:space:]]*SEATUNNEL_IMAGE[[:space:]]*=/ {
    if (!replaced) {
      print "SEATUNNEL_IMAGE=" image
      replaced = 1
    }
    next
  }
  { print }
  END {
    if (!replaced) print "SEATUNNEL_IMAGE=" image
  }
' "$env_file" > "$env_tmp"
chmod 0600 "$env_tmp"
mv "$env_tmp" "$env_file"

compose_base="$compose_root/docker-compose.yml"
compose_overlay="$compose_root/seatunnel/seatunnel-compose.yml"
SEATUNNEL_IMAGE="$image_ref" docker compose --env-file "$env_file" \
  -f "$compose_base" -f "$compose_overlay" config --quiet
SEATUNNEL_IMAGE="$image_ref" docker compose --env-file "$env_file" \
  -f "$compose_base" -f "$compose_overlay" up -d seatunnel-master control-plane
printf '%s\n' "$timestamp" > "$state_dir/active-backup"
activation_state=activated
trap - EXIT HUP INT TERM
printf '%s\n' "Activated SeaTunnel image: $image_ref"
