-- G16b：EP 域首批 9 表的 Doris ods_ep 建表（幂等，CREATE IF NOT EXISTS）。
-- 依据：docs/ep-domain-inventory-20260902.md §四选表与 nine-cols 列元数据（2026-09-02 源库实查）。
-- 模型：全部 UNIQUE KEY(首列主键) —— 增量重放与重跑按主键 UPSERT 幂等（对齐
-- G5 边缘表口径；ep_mz_cfzb 当年由 SeaTunnel 自动建表无 UNIQUE KEY，不复制该形态）。
-- 敏感列排除（硬约束，见 ep-domain-expansion-plan §4.1）：PATIENT 不建
--   PASSWORD / WECHAT_OPEN_ID / CREDENTIALS 三列，采集查询同列清单。
-- 类型映射：BIGINT/INT/TINYINT 直通，BIT→BOOLEAN，VARCHAR(n)/VARCHAR2(n)→VARCHAR(n)，
--   TEXT→STRING，TIMESTAMP→DATETIME。执行账号：root（存算分离默认 s3_vault）。

CREATE TABLE IF NOT EXISTS ods_ep.ep_status (
  `ID` BIGINT NOT NULL COMMENT '主键',
  `EP_ID` BIGINT NULL COMMENT '处方平台内部 ID',
  `QR_CODE` VARCHAR(100) NULL,
  `APPROVAL_COMMENT` VARCHAR(900) NULL,
  `INSTRUCTION` VARCHAR(900) NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `STOCK_STORE_ID` BIGINT NULL,
  `DS_REJECT_COMMENT` VARCHAR(900) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列',
  `REVIEW_USER_ID` BIGINT NULL,
  `REVIEW_USER_NAME` VARCHAR(200) NULL,
  `REVIEW_TIME` DATETIME NULL,
  `REVIEW_RESULT` STRING NULL,
  `AMOUNT` BIGINT NULL,
  `REVIEW_PUSH_NUM` INT NULL,
  `REVIEW_PUSH_TIME` DATETIME NULL,
  `VALID` TINYINT NULL,
  `SOURCE_TYPE` VARCHAR(50) NULL,
  `EXT` VARCHAR(900) NULL,
  `REVIEW_STATUS` INT NULL,
  `PAY_STATUS` TINYINT NULL,
  `DISPENSE_STATUS` TINYINT NULL,
  `MATCH_SUCCESS` BOOLEAN NULL,
  `ACCEPTED` BOOLEAN NULL,
  `CANCELED` BOOLEAN NULL,
  `USED` BOOLEAN NULL,
  `SELECTED` BOOLEAN NULL,
  `UPLOAD_SIGNED_RX` BOOLEAN NULL,
  `FLOW_TYPE` VARCHAR(50) NULL,
  `PAYMENT_TYPE` TINYINT NULL,
  `UPLOAD_RX_FILE` TINYINT NULL,
  `APPROVAL_REJECT_TYPE` VARCHAR(16) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_chain (
  `ID` BIGINT NOT NULL COMMENT '主键',
  `EP_ID` BIGINT NULL COMMENT '处方平台内部 ID',
  `OPERATION` VARCHAR(200) NULL,
  `INFO` STRING NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列',
  `VALID` TINYINT NULL,
  `PRE_STATUS` TINYINT NULL,
  `STATUS` TINYINT NULL,
  `CIRCULATION_STATUS` TINYINT NULL,
  `CREATE_BY` VARCHAR(50) NULL,
  `EP_FLOW_ID` BIGINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_yb_rx (
  `HI_RXNO` VARCHAR(100) NOT NULL COMMENT '医保处方号（主键）',
  `SOURCE` VARCHAR(100) NOT NULL,
  `INSTITUTION_CODE` VARCHAR(100) NOT NULL,
  `PATIENT_IDENTITY` VARCHAR(100) NOT NULL COMMENT '医保患者身份串（T5b 第三身份形态）',
  `RX_TRACE_CODE` VARCHAR(100) NOT NULL,
  `DC_SIGN` STRING NULL,
  `DC_SIGN_FILE` STRING NULL,
  `RX_INFO` STRING NULL,
  `RX_DRUG_DETAIL` STRING NULL,
  `MDTRT_INFO` STRING NULL,
  `RX_DISE_LIST` STRING NULL,
  `RX_UPLOAD_INFO` STRING NULL,
  `RX_CANCEL_INFO` STRING NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NOT NULL COMMENT '增量水位列',
  `PHAR_SIGN` STRING NULL
) ENGINE=OLAP
UNIQUE KEY(`HI_RXNO`)
DISTRIBUTED BY HASH(`HI_RXNO`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_tag (
  `ID` INT NOT NULL COMMENT '主键',
  `EP_ID` BIGINT NULL COMMENT '处方平台内部 ID',
  `CATEGORY` VARCHAR(50) NULL,
  `TYPE` VARCHAR(50) NULL,
  `TAG` VARCHAR(100) NULL,
  `CONTENT` VARCHAR(2048) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列'
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_flow (
  `ID` INT NOT NULL COMMENT '主键',
  `EP_ID` BIGINT NULL COMMENT '处方平台内部 ID',
  `DRUGSTORE_ID` BIGINT NULL,
  `SELECT_DRUGSTORE_TIME` DATETIME NULL,
  `REVIEW_USER_ID` BIGINT NULL,
  `REVIEW_USER_NAME` VARCHAR(200) NULL,
  `REVIEW_TIME` DATETIME NULL,
  `REVIEW_TYPE` VARCHAR(10) NULL,
  `REVIEW_COMMENT` VARCHAR(256) NULL,
  `INSTRUCTION` VARCHAR(256) NULL,
  `REVIEW_STATUS` TINYINT NULL,
  `PAY_STATUS` TINYINT NULL,
  `DISPENSE_STATUS` TINYINT NULL,
  `SELECTED` BOOLEAN NULL,
  `ACCEPTED` BOOLEAN NULL,
  `USED` BOOLEAN NULL,
  `UPLOAD_SIGNED_RX` BOOLEAN NULL,
  `AMOUNT` BIGINT NULL,
  `END_FLAG` BOOLEAN NULL,
  `END_TYPE` VARCHAR(256) NULL,
  `END_TIME` DATETIME NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列',
  `DEL` BOOLEAN NULL,
  `TARGET_TYPE` VARCHAR(10) NULL,
  `PATIENT_ID` BIGINT NULL COMMENT '患者域关联键',
  `PATIENT_NAME` VARCHAR(50) NULL COMMENT '患者姓名（PHI，仓内有 API 面无）',
  `MEDICARE_REVIEW_COMMENT` VARCHAR(1000) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

-- PATIENT：敏感列 PASSWORD / WECHAT_OPEN_ID / CREDENTIALS 不建列（G16b 硬约束）
CREATE TABLE IF NOT EXISTS ods_ep.patient (
  `ID` BIGINT NOT NULL COMMENT '患者主档主键',
  `CARD_NUMBER` VARCHAR(100) NULL COMMENT '证件号（PHI，仓内有 API 面无）',
  `GENDER` VARCHAR(10) NULL,
  `BIRTHDAY` INT NULL,
  `NAME` VARCHAR(200) NULL COMMENT '患者姓名（PHI，仓内有 API 面无）',
  `PHONE` VARCHAR(100) NULL COMMENT '联系方式（PHI，仓内有 API 面无）',
  `SOURCE` VARCHAR(100) NULL COMMENT '注册来源（C 端采集路径）',
  `DEL` INT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列',
  `CREATE_BY` VARCHAR(30) NULL,
  `UPDATE_BY` VARCHAR(30) NULL,
  `REAL_NAME_AUTHENTICATION` TINYINT NULL,
  `CARD_TYPE` VARCHAR(2) NULL,
  `WEIGHT` VARCHAR(10) NULL,
  `HEIGHT` VARCHAR(10) NULL,
  `REAL_NAME_AUTHENTICATION_TIME` DATETIME NULL,
  `REAL_NAME_AUTHENTICATION_ADDRESS` VARCHAR(200) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.patient_card (
  `ID` BIGINT NOT NULL COMMENT '就诊卡主键',
  `CARD_NUMBER` VARCHAR(100) NULL COMMENT '卡号（PHI，仓内有 API 面无）',
  `NAME` VARCHAR(50) NULL COMMENT '持卡人姓名（PHI）',
  `RELATIONSHIP` VARCHAR(20) NULL COMMENT '与主体关系（亲情账号）',
  `INSTITUTION_ID` BIGINT NULL,
  `INSTITUTION_NAME` VARCHAR(100) NULL,
  `PATIENT_ID` BIGINT NULL COMMENT '患者域关联键',
  `CREATE_TIME` DATETIME NULL,
  `STATE` TINYINT NULL,
  `DEL` INT NULL,
  `CARD_TYPE` VARCHAR(20) NULL,
  `GENDER` VARCHAR(10) NULL,
  `UPDATE_TIME` DATETIME NOT NULL COMMENT '增量水位列'
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.patient_ep_record (
  `ID` BIGINT NOT NULL COMMENT '主键',
  `PATIENT_ID` BIGINT NULL COMMENT '患者域关联键',
  `EP_ID` BIGINT NULL COMMENT '处方域关联键',
  `TYPE` VARCHAR(50) NULL,
  `OPERATION` VARCHAR(50) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列',
  `DEL` TINYINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_drug_ext (
  `ID` BIGINT NOT NULL COMMENT '主键',
  `EP_ID` BIGINT NULL COMMENT '处方平台内部 ID',
  `EP_DRUG_ID` BIGINT NULL,
  `DRUG_STOCK_ID` BIGINT NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `UNIT_PRICE` INT NULL,
  `NUM` INT NULL,
  `AMOUNT` BIGINT NULL,
  `SNAPSHOT` STRING NULL,
  `VALID` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL COMMENT '增量水位列'
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");
