-- G16c：EP 域二批 8 表（ORDER 交易域 6 + 机构维度 2）的 Doris ods_ep 建表
-- （幂等，CREATE IF NOT EXISTS）。依据 docs/ep-domain-inventory-20260902.md §六
-- 二批候选与 2026-09-03 源库列元数据/PK/FK 聚合预检（全部 0 孤儿、PK/SN 全唯一）。
-- 命名偏差（如实记录）：源表 ORDER 为 SQL 保留字，交易域 6 表统一加 ep_ 前缀
-- （ep_order / ep_order_item / ep_order_flow / ep_order_trade /
--  ep_order_relationship / ep_order_after_sale）；机构维度保持原名小写。
-- 长度口径沿用 G16b 教训：DM VARCHAR 按字符、Doris 按字节，一律 VARCHAR(65533)
-- 宽松形态（DECIMAL(20,0) 直通，NUMBER 无精度 → DECIMAL(38,10)，TEXT→STRING）。
CREATE TABLE IF NOT EXISTS ods_ep.ep_order (
  `ID` BIGINT NOT NULL,
  `SN` VARCHAR(65533) NULL,
  `TYPE` INT NULL,
  `EP_ID` BIGINT NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `DRUGSTORE_NAME` VARCHAR(65533) NULL,
  `PATIENT_ID` BIGINT NULL,
  `PATIENT_NAME` VARCHAR(65533) NULL,
  `TRANSACTION_ID` VARCHAR(65533) NULL,
  `AMOUNT` DECIMAL(20,0) NULL,
  `GOODS_AMOUNT` BIGINT NULL,
  `FREIGHT` BIGINT NULL,
  `TRANSACTION_FEE` DECIMAL(20,0) NULL,
  `COMMISSION_FEE` DECIMAL(20,0) NULL,
  `PAYMENT_TYPE` INT NULL,
  `ORDER_STATUS` INT NULL,
  `EP_STATUS` TINYINT NULL,
  `PAY_STATUS` INT NULL,
  `DELIVERY_STATUS` INT NULL,
  `CIRCULATION_STATUS` TINYINT NULL,
  `CONSIGNEE_ADDRESS_ID_PATH` VARCHAR(65533) NULL,
  `CONSIGNEE_ADDRESS_PATH` VARCHAR(65533) NULL,
  `CONSIGNEE_DETAIL` VARCHAR(65533) NULL,
  `CONSIGNEE_MOBILE` VARCHAR(65533) NULL,
  `CONSIGNEE_NAME` VARCHAR(65533) NULL,
  `LOGISTICS_CODE` VARCHAR(65533) NULL,
  `LOGISTICS_NAME` VARCHAR(65533) NULL,
  `LOGISTICS_NO` VARCHAR(65533) NULL,
  `LOGISTICS_TIME` DATETIME NULL,
  `DELIVERY_METHOD` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `COMPLETE_TIME` DATETIME NULL,
  `PID` INT NULL,
  `LOGISTICS_BILL` BIGINT NULL,
  `QR_CODE` VARCHAR(65533) NULL,
  `DISPENSE_STATUS` TINYINT NULL,
  `DISPENSE_TIME` DATETIME NULL,
  `REFUND_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `PAY_TIME` DATETIME NULL,
  `SOURCE_TYPE` VARCHAR(65533) NULL,
  `EXT` VARCHAR(65533) NULL,
  `MEDICARE_AMOUNT` BIGINT NULL,
  `CASH_AMOUNT` BIGINT NULL,
  `PAY_INITIATED_TIME` DATETIME NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_order_item (
  `ID` BIGINT NOT NULL,
  `SN` VARCHAR(65533) NULL,
  `ORDER_SN` VARCHAR(65533) NULL,
  `DRUG_NAME` VARCHAR(65533) NULL,
  `PRODUCE_CO` VARCHAR(65533) NULL,
  `SPEC` VARCHAR(65533) NULL,
  `CODE` VARCHAR(65533) NULL,
  `UNIT_PRICE` INT NULL,
  `NUM` INT NULL,
  `AMOUNT` INT NULL,
  `EP_DRUG_ID` BIGINT NULL,
  `DRUG_STOCK_ID` BIGINT NULL,
  `SNAPSHOT` STRING NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `COMMENT_STATUS` VARCHAR(65533) NULL,
  `EP_ID` BIGINT NULL,
  `BCHNO` VARCHAR(65533) NULL,
  `MANU_LOTNUM` VARCHAR(65533) NULL,
  `TRACE_CODE` VARCHAR(65533) NULL,
  `RTAL_DOCNO` VARCHAR(65533) NULL,
  `PROD_DATE` VARCHAR(65533) NULL,
  `VALID_DATE` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_order_flow (
  `ID` BIGINT NOT NULL,
  `SN` VARCHAR(65533) NULL,
  `ORDER_SN` VARCHAR(65533) NULL,
  `EP_ID` BIGINT NULL,
  `EP_NAME` VARCHAR(65533) NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `DRUGSTORE_NAME` VARCHAR(65533) NULL,
  `PATIENT_ID` BIGINT NULL,
  `PATIENT_NAME` VARCHAR(65533) NULL,
  `TRANSACTION_ID` VARCHAR(65533) NULL,
  `SEQUENCE` INT NULL,
  `FLOW_TYPE` TINYINT NULL,
  `AMOUNT` DECIMAL(20,0) NULL,
  `TRANSACTION_FEE` DECIMAL(20,0) NULL,
  `COMMISSION_FEE` DECIMAL(20,0) NULL,
  `FLOW_AMOUNT` DECIMAL(20,0) NULL,
  `PAYMENT_TYPE` INT NULL,
  `CREATE_TIME` DATETIME NULL,
  `BALANCE` DECIMAL(20,0) NULL,
  `FREIGHT` BIGINT NULL,
  `GOODS_AMOUNT` BIGINT NULL,
  `UPDATE_TIME` DATETIME NULL,
  `MEDICARE_AMOUNT` BIGINT NULL,
  `CASH_AMOUNT` BIGINT NULL,
  `CHANNEL` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_order_trade (
  `ID` BIGINT NOT NULL,
  `SN` VARCHAR(65533) NULL,
  `ORDER_SN` VARCHAR(65533) NULL,
  `TRANSACTION_ID` VARCHAR(65533) NULL,
  `EP_ID` BIGINT NULL,
  `INSTITUTION_ID` BIGINT NULL,
  `INSTITUTION_NAME` VARCHAR(65533) NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `DRUGSTORE_NAME` VARCHAR(65533) NULL,
  `PATIENT_ID` BIGINT NULL,
  `PATIENT_NAME` VARCHAR(65533) NULL,
  `AMOUNT` DECIMAL(20,0) NULL,
  `INFO` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `CHANNEL` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_order_relationship (
  `ID` BIGINT NOT NULL,
  `ORDER_SN` VARCHAR(65533) NULL,
  `EP_ID` BIGINT NULL,
  `VALID` DECIMAL(38,10) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `EP_FLOW_ID` BIGINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.ep_order_after_sale (
  `ID` BIGINT NOT NULL,
  `SN` VARCHAR(65533) NULL,
  `ORDER_SN` VARCHAR(65533) NULL,
  `DRUGSTORE_ID` BIGINT NULL,
  `DRUGSTORE_NAME` VARCHAR(65533) NULL,
  `PATIENT_ID` BIGINT NULL,
  `PATIENT_NAME` VARCHAR(65533) NULL,
  `SERVICE_TYPE` VARCHAR(65533) NULL,
  `APPLY_REASON` VARCHAR(65533) NULL,
  `REFUSE_REASON` VARCHAR(65533) NULL,
  `REVIEW_DESCRIPTION` VARCHAR(65533) NULL,
  `REVIEW_TIME` DATETIME NULL,
  `SERVICE_STATUS` VARCHAR(65533) NULL,
  `REFUND_WAY` VARCHAR(65533) NULL,
  `REFUND_TIME` DATETIME NULL,
  `ORDER_AMOUNT` BIGINT NULL,
  `ORDER_DRUG_AMOUNT` BIGINT NULL,
  `ORDER_FREIGHT` BIGINT NULL,
  `APPLY_REFUND_AMOUNT` BIGINT NULL,
  `ACTUAL_REFUND_AMOUNT` BIGINT NULL,
  `ACTUAL_REFUND_DRUG_AMOUNT` BIGINT NULL,
  `ACTUAL_REFUND_FREIGHT` BIGINT NULL,
  `SOURCE_TYPE` VARCHAR(65533) NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `DEL` TINYINT NULL,
  `PHOTO_LINK` VARCHAR(65533) NULL,
  `APPLY_DESCRIPTION` VARCHAR(65533) NULL,
  `RETRY_COUNT` INT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution (
  `ID` BIGINT NOT NULL,
  `GROUP_ID` INT NULL,
  `CODE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `PHONE` VARCHAR(65533) NULL,
  `CITY` VARCHAR(65533) NULL,
  `ADDRESS` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `DEL` INT NULL,
  `HOSP_TYPE` VARCHAR(65533) NULL,
  `UNIFIED_CREDIT_CODE` VARCHAR(65533) NULL,
  `ORGANIZATION_CODE` VARCHAR(65533) NULL,
  `INSTITUTION_TYPE` VARCHAR(65533) NULL,
  `LEVEL` VARCHAR(65533) NULL,
  `CATEGORY` VARCHAR(65533) NULL,
  `CREDENTIALS` VARCHAR(65533) NULL,
  `HAS_INTERNET_HOSPITAL` TINYINT NULL,
  `WEIGHT` TINYINT NULL,
  `SHORT_NAME` VARCHAR(65533) NULL,
  `CONTACT` VARCHAR(65533) NULL,
  `MEDICARE_CODE` VARCHAR(65533) NULL,
  `MEDICARE_FIXED_POINT` TINYINT NULL,
  `APPROVE_ORG` VARCHAR(65533) NULL,
  `LEGAL_REPRESENTATIVE` VARCHAR(65533) NULL,
  `REGISTER_NO` VARCHAR(65533) NULL,
  `PRINCIPAL` VARCHAR(65533) NULL,
  `BUSINESS_NATURE` VARCHAR(65533) NULL,
  `DIAGNOSIS_SUBJECT` VARCHAR(65533) NULL,
  `CUSTOMER_NAME` VARCHAR(65533) NULL,
  `CUSTOMER_PHONE` VARCHAR(65533) NULL,
  `STATUS` VARCHAR(65533) NULL,
  `BA_STATUS` VARCHAR(65533) NULL,
  `PRINCIPAL_TYPE` VARCHAR(65533) NULL,
  `APPLICANT_NAME` VARCHAR(65533) NULL,
  `APPLICATION_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `BA_TYPE` VARCHAR(65533) NULL,
  `BA_VALID` TINYINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_info (
  `ID` BIGINT NOT NULL,
  `CODE` VARCHAR(65533) NULL,
  `FRONTEND_ADDRESS` VARCHAR(65533) NULL,
  `API` VARCHAR(65533) NULL,
  `ENABLE` BIGINT NULL,
  `SETTING` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

