-- G16d：EP 域三批 14 表（机构药品目录系 7 + 药品主数据 5 + 患者用药/地址 2）
-- 的 Doris ods_ep 建表（幂等，CREATE IF NOT EXISTS）。依据
-- docs/ep-domain-inventory-20260902.md §六与 2026-09-03 源库预检（14 表 PK 全唯一；
-- FK 干净边 6 条在册：detail/log/verify→submit、verify_detail→verify[1 孤儿不注册]、
-- medicine/address→patient、inst_drug_catalog→institution；脏边见 gate 报告 §三）。
-- 水位例外：institution_drug_catalog_submit_log 无 UPDATE_TIME，增量水位用 CREATE_TIME。
-- 长度口径沿用 G16b：DM VARCHAR 按字符、Doris 按字节，一律 VARCHAR(65533)。
CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog (
  `ID` INT NOT NULL,
  `INSTITUTION_ID` BIGINT NULL,
  `INSTITUTION_NAME` VARCHAR(65533) NULL,
  `DATABASE_ID` VARCHAR(65533) NULL,
  `STATUS` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `ENABLED_DATE` DATETIME NULL,
  `DISABLED_DATE` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `NOTICE` VARCHAR(65533) NULL,
  `REMARK` VARCHAR(65533) NULL,
  `VERSION` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_detail (
  `ID` INT NOT NULL,
  `SUBMIT_ID` BIGINT NULL,
  `DATABASE_ID` VARCHAR(65533) NULL,
  `REPLACE_DATABASE_ID` VARCHAR(65533) NULL,
  `NOTICE` VARCHAR(65533) NULL,
  `STATUS` TINYINT NULL,
  `UPDATE_TYPE` VARCHAR(65533) NULL,
  `REMARK` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `DEL` TINYINT NULL,
  `VERSION` VARCHAR(65533) NULL,
  `CATALOG_CHANGED` TINYINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_record (
  `ID` INT NOT NULL,
  `DRUG_CATALOG_ID` BIGINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `OPERATION_TYPE` VARCHAR(65533) NULL,
  `ENABLED_DATE` DATETIME NULL,
  `DISABLED_DATE` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `REMARK` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_submit (
  `ID` INT NOT NULL,
  `INSTITUTION_ID` BIGINT NULL,
  `INSTITUTION_NAME` VARCHAR(65533) NULL,
  `SIGNATURE_FILE` VARCHAR(65533) NULL,
  `CREATE_USER_ID` BIGINT NULL,
  `STATUS` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `DEL` TINYINT NULL,
  `NODE` VARCHAR(65533) NULL,
  `EXT` VARCHAR(65533) NULL,
  `FLOW_VERSION` INTEGER NULL,
  `ANTIMICROBIAL_SIGNATURE_FILE` VARCHAR(65533) NULL,
  `STOCK_VERIFY_SUBJECT` VARCHAR(65533) NULL,
  `PUBLISH_TIME` DATETIME NULL,
  `RETURN_MEDICATION_POLICY_FILE` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_submit_log (
  `ID` BIGINT NOT NULL,
  `SUBMIT_ID` BIGINT NULL,
  `NODE` VARCHAR(65533) NULL,
  `NODE_LABEL` VARCHAR(65533) NULL,
  `OPERATOR_NAME` VARCHAR(65533) NULL,
  `OPERATOR_PHONE` VARCHAR(65533) NULL,
  `COMPANY_NAME` VARCHAR(65533) NULL,
  `REJECT_REASON` VARCHAR(65533) NULL,
  `THEME` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `DEL` INTEGER NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_verify (
  `ID` INT NOT NULL,
  `DRUGSTORE_COMPANY_ID` BIGINT NULL,
  `DRUGSTORE_COMPANY_NAME` VARCHAR(65533) NULL,
  `SUBMIT_ID` BIGINT NULL,
  `VERIFY_USER_ID` BIGINT NULL,
  `VERIFY_USER_NAME` VARCHAR(65533) NULL,
  `STATUS` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.institution_drug_catalog_verify_detail (
  `ID` INT NOT NULL,
  `VERIFY_ID` BIGINT NULL,
  `STATUS` TINYINT NULL,
  `DATABASE_ID` VARCHAR(65533) NULL,
  `RELATED_DATABASE_ID` VARCHAR(65533) NULL,
  `REMARK` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `EXT` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.drug_database (
  `ID` VARCHAR(65533) NOT NULL,
  `CATEGORY` VARCHAR(65533) NULL,
  `PROVINCE_DRUG_CODE` VARCHAR(65533) NULL,
  `LOCAL_CODE` VARCHAR(65533) NULL,
  `MEDICARE_CODE` VARCHAR(65533) NULL,
  `STANDARD_CODE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `PRODUCT_NAME` VARCHAR(65533) NULL,
  `PRODUCE_COMPANY` VARCHAR(65533) NULL,
  `PACKAGING_COMPANY` VARCHAR(65533) NULL,
  `REGISTERED_DOSAGE_FORM` VARCHAR(65533) NULL,
  `ACTUAL_DOSAGE_FORM` VARCHAR(65533) NULL,
  `REGISTERED_SPECIFICATION` VARCHAR(65533) NULL,
  `ACTUAL_SPECIFICATION` VARCHAR(65533) NULL,
  `PACKAGING_MATERIAL` VARCHAR(65533) NULL,
  `MIN_PACKAGE_QUANTITY` VARCHAR(65533) NULL,
  `MIN_PACKAGE_UNIT` VARCHAR(65533) NULL,
  `MIN_DOSAGE_UNIT` VARCHAR(65533) NULL,
  `PRICING_UNIT` VARCHAR(65533) NULL,
  `PERMIT_NO` VARCHAR(65533) NULL,
  `PRESCRIPTION_FLAG` VARCHAR(65533) NULL,
  `CHARGE_ITEM_LEVEL` VARCHAR(65533) NULL,
  `RESTRICTION_FLAG` VARCHAR(65533) NULL,
  `RESTRICTION_DESCRIPTION` VARCHAR(65533) NULL,
  `MEDICAL_INSURANCE_NEGOTIATED_PRICE` VARCHAR(65533) NULL,
  `ADMINISTRATIVE_LEVEL` VARCHAR(65533) NULL,
  `MEDICAL_INSURANCE_PAYMENT_LIMIT` VARCHAR(65533) NULL,
  `SELECTED_PRICE` VARCHAR(65533) NULL,
  `CONSISTENCY_EVALUATION_FLAG` VARCHAR(65533) NULL,
  `OUTPATIENT_SPECIFIC_DISEASES` VARCHAR(65533) NULL,
  `TWO_DISEASES` VARCHAR(65533) NULL,
  `CENTRALIZED_PURCHASE_DRUG` VARCHAR(65533) NULL,
  `SEPARATE_PAYMENT_FLAG` VARCHAR(65533) NULL,
  `CHARITY_SPECIAL_DISEASE_CATEGORY` VARCHAR(65533) NULL,
  `MEDICAL_INSURANCE_BILLING_CYCLE_QTY` VARCHAR(65533) NULL,
  `CHARITY_AID_CYCLE_QTY` VARCHAR(65533) NULL,
  `BILLING_CYCLE` VARCHAR(65533) NULL,
  `BASIC_MI_ENABLE_FLAG` VARCHAR(65533) NULL,
  `BASIC_MI_START_DATE` VARCHAR(65533) NULL,
  `BASIC_MI_END_DATE` VARCHAR(65533) NULL,
  `MATERNITY_INSURANCE_ENABLE_FLAG` VARCHAR(65533) NULL,
  `MATERNITY_INSURANCE_START_DATE` VARCHAR(65533) NULL,
  `MATERNITY_INSURANCE_END_DATE` VARCHAR(65533) NULL,
  `DEPENDENT_POOLING_ENABLE_FLAG` VARCHAR(65533) NULL,
  `DEPENDENT_POOLING_START_DATE` VARCHAR(65533) NULL,
  `DEPENDENT_POOLING_END_DATE` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `RECORD_ID` BIGINT NULL,
  `DEL` TINYINT NULL,
  `STD` TINYINT NULL,
  `REFER_STD` TINYINT NULL,
  `SOURCE` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.drug_catalog (
  `ID` BIGINT NOT NULL,
  `SOURCE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `GENERIC_NAME` VARCHAR(65533) NULL,
  `PERMIT_NO` VARCHAR(65533) NULL,
  `PRODUCE_CO` VARCHAR(65533) NULL,
  `DOSAGE_FORM` VARCHAR(65533) NULL,
  `DRUG_SPECIFICATION` VARCHAR(65533) NULL,
  `DRUG_UNIT` VARCHAR(65533) NULL,
  `DRUG_PACKAGE_SPECIFICATION` VARCHAR(65533) NULL,
  `DRUG_PACKAGE_UNIT` VARCHAR(65533) NULL,
  `STANDARD_CODE` VARCHAR(65533) NULL,
  `MEDICARE_CODE` VARCHAR(65533) NULL,
  `YPID` VARCHAR(65533) NULL,
  `STATUS` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `ENABLED_DATE` DATETIME NULL,
  `DISABLED_DATE` DATETIME NULL,
  `DRUG_DOS_UNIT` VARCHAR(65533) NULL,
  `DRUG_DOS_SPEC` VARCHAR(65533) NULL,
  `GENERIC_NAME_SPELL` VARCHAR(65533) NULL,
  `UPDATE_TIME` DATETIME NULL,
  `INSTITUTION_DRUG_CATALOG_ID` BIGINT NULL,
  `REMARK` VARCHAR(65533) NULL,
  `NOTICE` VARCHAR(65533) NULL,
  `RELATIONSHIP_CODE` VARCHAR(65533) NULL,
  `CATEGORY` VARCHAR(65533) NULL,
  `RELATIONSHIP_DATABASE_RECORD_ID` BIGINT NULL,
  `SUPERVISION` TINYINT NULL,
  `IN_DATABASE` TINYINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.drug_category (
  `ID` BIGINT NOT NULL,
  `TYPE` VARCHAR(65533) NULL,
  `CODE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `LEVEL1` VARCHAR(65533) NULL,
  `LEVEL2` VARCHAR(65533) NULL,
  `LEVEL3` VARCHAR(65533) NULL,
  `LEVEL4` VARCHAR(65533) NULL,
  `LEVEL5` VARCHAR(65533) NULL,
  `LEVEL6` VARCHAR(65533) NULL,
  `UPDATE_TIME` DATETIME NULL,
  `CREATE_TIME` DATETIME NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.drugstore (
  `ID` BIGINT NOT NULL,
  `GROUP_ID` INTEGER NULL,
  `CODE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `SHORT_NAME` VARCHAR(65533) NULL,
  `TYPE` VARCHAR(65533) NULL,
  `RETAIL_TYPE` VARCHAR(65533) NULL,
  `PHONE` VARCHAR(65533) NULL,
  `CONTACT` VARCHAR(65533) NULL,
  `CONTACT_PHONE` VARCHAR(65533) NULL,
  `CONTACT_ID_CARD` VARCHAR(65533) NULL,
  `MANAGER_NAME` VARCHAR(65533) NULL,
  `MANAGER_PHONE` VARCHAR(65533) NULL,
  `LEGAL_PERSON_NAME` VARCHAR(65533) NULL,
  `LEGAL_PERSON_ID_CARD_TYPE` VARCHAR(65533) NULL,
  `LEGAL_PERSON_ID_CARD` VARCHAR(65533) NULL,
  `BANK_ACCOUNT` VARCHAR(65533) NULL,
  `BANK_NAME` VARCHAR(65533) NULL,
  `CITY` VARCHAR(65533) NULL,
  `ADDRESS` VARCHAR(65533) NULL,
  `OPEN_TIME` VARCHAR(65533) NULL,
  `LATITUDE` VARCHAR(65533) NULL,
  `LONGITUDE` VARCHAR(65533) NULL,
  `LICENSE_FILE_ID` BIGINT NULL,
  `STATUS` VARCHAR(65533) NULL,
  `DELIVERY_METHOD` VARCHAR(65533) NULL,
  `CREDENTIALS` CLOB NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `DEL` TINYINT NULL,
  `PAYMENT_TYPE` VARCHAR(65533) NULL,
  `PAYMENT_CLIENT_ID` VARCHAR(65533) NULL,
  `FK_ID` VARCHAR(65533) NULL,
  `DATASOURCE_ID` VARCHAR(65533) NULL,
  `SETTING` CLOB NULL,
  `MEDICARE_FIXED_POINT` TINYINT NULL,
  `COMPANY_ID` BIGINT NULL,
  `UNIFIED_CREDIT_CODE` VARCHAR(65533) NULL,
  `SOURCE` VARCHAR(65533) NULL,
  `SD_MEDICARE` TINYINT NULL,
  `STD_MEDICARE` TINYINT NULL,
  `MEDICARE_CODE` VARCHAR(65533) NULL,
  `BA_STATUS` VARCHAR(65533) NULL,
  `SUPPORT_RESERVATION` TINYINT NULL,
  `BUSINESS_LICENSE_NO` VARCHAR(65533) NULL,
  `BUSINESS_LICENSE_PERIOD` VARCHAR(65533) NULL,
  `DRUG_LICENSE_NO` VARCHAR(65533) NULL,
  `DRUG_LICENSE_PERIOD` VARCHAR(65533) NULL,
  `DRUG_LICENSE_ADDRESS` VARCHAR(65533) NULL,
  `DRUG_LICENSE_SCOPE` CLOB NULL,
  `DRUG_LICENSE_METHOD` VARCHAR(65533) NULL,
  `DRUG_LICENSE_MANAGER` VARCHAR(65533) NULL,
  `DRUG_LICENSE_PHONE` VARCHAR(65533) NULL,
  `DRUG_LICENSE_FILE_ID` BIGINT NULL,
  `EMS_MERCHANT_NO` VARCHAR(65533) NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `DRUG_LICENSE_CITY` VARCHAR(65533) NULL,
  `APPLICANT_NAME` VARCHAR(65533) NULL,
  `APPLICATION_TIME` DATETIME NULL,
  `BA_TYPE` VARCHAR(65533) NULL,
  `BA_VALID` TINYINT NULL,
  `SF_MERCHANT_NO` VARCHAR(65533) NULL,
  `SPECIAL_REMARK` VARCHAR(65533) NULL,
  `BUSINESS_LICENSE_MANAGER` VARCHAR(65533) NULL,
  `DRUG_LICENSE_QUALITY_MANAGER` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.disease_catalog (
  `ID` BIGINT NOT NULL,
  `TYPE` VARCHAR(65533) NULL,
  `NAME` VARCHAR(65533) NULL,
  `CODE` VARCHAR(65533) NULL,
  `MAIN_OPERATION_WAY` VARCHAR(65533) NULL,
  `OPERATION_CODE` VARCHAR(65533) NULL,
  `MAINTAIN_SUBJECT` VARCHAR(65533) NULL,
  `CREATE_BY` VARCHAR(65533) NULL,
  `UPDATE_BY` VARCHAR(65533) NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `DEL` TINYINT NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.patient_medicine (
  `ID` BIGINT NOT NULL,
  `PATIENT_ID` BIGINT NULL,
  `EP_ID` BIGINT NULL,
  `EP_DRUG_ID` BIGINT NULL,
  `MEDICINE_DATE` DATE NULL,
  `SORT` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

CREATE TABLE IF NOT EXISTS ods_ep.patient_address (
  `ID` BIGINT NOT NULL,
  `PATIENT_ID` BIGINT NULL,
  `CONTACT` VARCHAR(65533) NULL,
  `PHONE` VARCHAR(65533) NULL,
  `AREA_CODE` INT NULL,
  `CITY` VARCHAR(65533) NULL,
  `ADDRESS` VARCHAR(65533) NULL,
  `POST_CODE` VARCHAR(65533) NULL,
  `DEFAULT_ADDRESS` TINYINT NULL,
  `CREATE_TIME` DATETIME NULL,
  `UPDATE_TIME` DATETIME NULL,
  `DEL` INT NULL,
  `LATITUDE` VARCHAR(65533) NULL,
  `LONGITUDE` VARCHAR(65533) NULL
) ENGINE=OLAP
UNIQUE KEY(`ID`)
DISTRIBUTED BY HASH(`ID`) BUCKETS 1
PROPERTIES ("replication_num" = "1");

